language: node_js
addons:
  firefox: latest

node_js:
  - "0.10"

notifications:
  irc:
    channels:
      - "irc.mozilla.org#loop"
    use_notice: false
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch} - %{commit}: %{author}): %{message} %{build_url}"
#  email:
#    - talkilla-travis-results@mozilla.com
#    - on_success: change
#    - on_failure: change

install:
  - pip install --user -r require.pip
  - npm install

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
